# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Generate Environment Variables
        # run: |
        #   echo "JWT_SECRET=$JWT_SECRET" >> .env.JWT_SECRET
        #   echo "NODE_ENV=$NODE_ENV" >> .env.NODE_ENV
        #   echo "DB=$DB" >> .env.DB
        #   echo "DB_HOST=$DB_HOST" >> .env.DB_HOST
        #   echo "DB_PORT=$DB_PORT" >> .env.DB_PORT
        #   echo "DB_USER=$DB_USER" >> .env.DB_USER
        #   echo "DB_PASSWORD" >> .env.DB_PASSWORD
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DB: ${{ secrets.DB }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - run: npm install
    - run: npm run coverage
